version: '3'

services:
  postgres-server:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=reading_log
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reading_log_db

volumes:
  pgdata:
